# SITE CONFIGURATION
baseurl: "/Reveal-Jekyll"
#url: "https://sylhare.github.io"
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Slides
collections:
  slides:
    output: true
    permalink: /:collection/:name
  basements:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea"]
